"""USPTO Open Data Portal (ODP) client and models.

This module provides async access to USPTO's Open Data Portal API for:
- Patent applications (search, metadata, documents, family graphs)
- Bulk data downloads
- Petition decisions
- PTAB trials, appeals, and interferences
"""

from .clients import (
    ApplicationsClient,
    BulkDataClient,
    PaginationModel,
    PetitionsClient,
    PtabAppealsClient,
    PtabInterferencesClient,
    PtabTrialsClient,
    SearchPayload,
    UsptoOdpBaseClient,
)
from .models import (
    # Application models
    Address,
    Applicant,
    ApplicationEvent,
    ApplicationMetaData,
    ApplicationRecord,
    ApplicationResponse,
    Assignee,
    AssigneeAddress,
    Assignment,
    AssignmentResponse,
    Assignor,
    Attorney,
    # Bulk Data
    BulkDataFile,
    BulkDataProduct,
    BulkDataProductResponse,
    BulkDataSearchResponse,
    ChildContinuity,
    ContinuityBag,
    CustomerNumberCorrespondenceData,
    DocumentMetaData,
    DocumentRecord,
    DocumentsResponse,
    EntityStatusData,
    FamilyEdge,
    FamilyGraphResponse,
    FamilyNode,
    # Base models
    FlexibleModel,
    ForeignPriority,
    Inventor,
    ParentContinuity,
    PatentTermAdjustmentData,
    PatentTermAdjustmentHistory,
    PersonName,
    # Petition Decisions
    PetitionDecision,
    PetitionDecisionDocument,
    PetitionDecisionFilter,
    PetitionDecisionIdentifierResponse,
    PetitionDecisionRange,
    PetitionDecisionResponse,
    PetitionDecisionSort,
    PetitionDecisionWithDocuments,
    # PTAB Appeals
    PtabAppeal,
    PtabAppealDecisionData,
    PtabAppealDocumentData,
    PtabAppealMetaData,
    PtabAppealRequestorData,
    PtabAppealResponse,
    PtabAppellantData,
    # PTAB Trials
    PtabDecisionData,
    PtabDerivationPetitionerData,
    PtabDocumentData,
    # PTAB Interferences
    PtabInterference,
    PtabInterferenceDocumentData,
    PtabInterferenceMetaData,
    PtabInterferencePartyData,
    PtabInterferenceResponse,
    PtabPatentOwnerData,
    PtabPetitionerData,
    PtabTrialDecision,
    PtabTrialDecisionResponse,
    PtabTrialDocument,
    PtabTrialDocumentResponse,
    PtabTrialMetaData,
    PtabTrialProceeding,
    PtabTrialProceedingResponse,
    RecordAttorney,
    SearchResponse,
    StrictModel,
    TelecommunicationAddress,
)

__all__ = [
    # Clients
    "ApplicationsClient",
    "BulkDataClient",
    "PetitionsClient",
    "PtabTrialsClient",
    "PtabAppealsClient",
    "PtabInterferencesClient",
    # Base client
    "UsptoOdpBaseClient",
    "SearchPayload",
    "PaginationModel",
    # Base models
    "StrictModel",
    "FlexibleModel",
    # Application models
    "Address",
    "TelecommunicationAddress",
    "PersonName",
    "Inventor",
    "Applicant",
    "Attorney",
    "Assignor",
    "Assignee",
    "AssigneeAddress",
    "Assignment",
    "AssignmentResponse",
    "ParentContinuity",
    "ChildContinuity",
    "ContinuityBag",
    "ForeignPriority",
    "PatentTermAdjustmentHistory",
    "PatentTermAdjustmentData",
    "ApplicationEvent",
    "DocumentMetaData",
    "EntityStatusData",
    "CustomerNumberCorrespondenceData",
    "RecordAttorney",
    "ApplicationMetaData",
    "ApplicationRecord",
    "SearchResponse",
    "ApplicationResponse",
    "DocumentRecord",
    "DocumentsResponse",
    "FamilyNode",
    "FamilyEdge",
    "FamilyGraphResponse",
    # Bulk Data
    "BulkDataFile",
    "BulkDataProduct",
    "BulkDataProductResponse",
    "BulkDataSearchResponse",
    # Petition Decisions
    "PetitionDecisionFilter",
    "PetitionDecisionRange",
    "PetitionDecisionSort",
    "PetitionDecisionDocument",
    "PetitionDecision",
    "PetitionDecisionWithDocuments",
    "PetitionDecisionResponse",
    "PetitionDecisionIdentifierResponse",
    # PTAB Trials
    "PtabTrialMetaData",
    "PtabPatentOwnerData",
    "PtabPetitionerData",
    "PtabDerivationPetitionerData",
    "PtabDocumentData",
    "PtabDecisionData",
    "PtabTrialProceeding",
    "PtabTrialProceedingResponse",
    "PtabTrialDocument",
    "PtabTrialDocumentResponse",
    "PtabTrialDecision",
    "PtabTrialDecisionResponse",
    # PTAB Appeals
    "PtabAppealMetaData",
    "PtabAppealDecisionData",
    "PtabAppellantData",
    "PtabAppealRequestorData",
    "PtabAppealDocumentData",
    "PtabAppeal",
    "PtabAppealResponse",
    # PTAB Interferences
    "PtabInterferenceMetaData",
    "PtabInterferencePartyData",
    "PtabInterferenceDocumentData",
    "PtabInterference",
    "PtabInterferenceResponse",
]
