"""Async client for the CanLII REST API.

CanLII covers Canadian courts, tribunals, statutes, and regulations with a
free API key. The IP-relevant slice includes Federal Court / Federal Court
of Appeal / Supreme Court IP rulings, Trade-marks Opposition Board (TMOB),
Patent Appeal Board (PAB), the Patent Act, and the Trademarks Act with
point-in-time legislation queries.
"""

from .api import (  # noqa: F401
    USAGE_RESOURCE_URI,
    BrowseCasesInput,
    BrowseLegislationInput,
    CanLIIClient,
    CaseDatabase,
    CaseDatabaseList,
    CaseId,
    CaseList,
    CaseMetadata,
    CaseRef,
    CitedCasesResponse,
    CitedLegislationRef,
    CitedLegislationsResponse,
    CitingCasesResponse,
    GetCaseInput,
    GetCitatorInput,
    GetLegislationInput,
    Language,
    LegislationDatabase,
    LegislationDatabaseList,
    LegislationList,
    LegislationMetadata,
    LegislationPart,
    LegislationRef,
    LegislationType,
    browse_cases,
    browse_legislation,
    get_case,
    get_cited_cases,
    get_cited_legislations,
    get_citing_cases,
    get_client,
    get_legislation,
    get_usage_resource,
    list_case_databases,
    list_legislation_databases,
)

__all__ = [
    "CanLIIClient",
    "BrowseCasesInput",
    "GetCaseInput",
    "GetCitatorInput",
    "BrowseLegislationInput",
    "GetLegislationInput",
    "list_case_databases",
    "browse_cases",
    "get_case",
    "get_cited_cases",
    "get_citing_cases",
    "get_cited_legislations",
    "list_legislation_databases",
    "browse_legislation",
    "get_legislation",
    "get_client",
    "CaseDatabase",
    "CaseDatabaseList",
    "CaseId",
    "CaseList",
    "CaseMetadata",
    "CaseRef",
    "CitedCasesResponse",
    "CitedLegislationRef",
    "CitedLegislationsResponse",
    "CitingCasesResponse",
    "Language",
    "LegislationDatabase",
    "LegislationDatabaseList",
    "LegislationList",
    "LegislationMetadata",
    "LegislationPart",
    "LegislationRef",
    "LegislationType",
    "USAGE_RESOURCE_URI",
    "get_usage_resource",
]
